### ISSUE TITLE
Generate output HTML that uses Tailwind

### ISSUE THREAD

**Issue by lloydjatkinson** [viashchuk/tooltip-generator#1]
Right now it generates the exact CSS classes you need etc. Could this tool optionally support generating HTML that uses Tailwind classes too? 😄

**Comment by viashchuk** [comment]
I really like your idea, but I can't decide which way to implement it.  🙈

1. Additionally, generate classes for tailwind.config (because default config will not work with classes like `pr-15` or `rounded-35`, because they are not declared in config).

2. Or add a switch between CSS and Tailwind to the sidebar and then use for all "input" the range of values that are in the default config (e.g., for the shadow, we can only use a few values `shadow-sm`).

What do you think is the best option? Or maybe you have some ideas? 💪

**Comment by lloydjatkinson** [comment]
Awesome! I think probably add a switch but also generate the extra classes (if the user goes outside of the range of defaults). The Tailwind tab could look something like:

```
Tailwind:

// Add these extra classes to your Tailwind configuration file.
// Read more here: https://tailwindcss.com/docs/configuration/

theme: {
    extend: {
        boxShadow: {
            3xl: '0 35px 60px -15px rgba(0, 0, 0, .3)',
        }
    }
}
```

Or you could go fully with option 2 to start with before adding support for extra classes 😊
